server:
  port: 8006

dubbo:
  application:
    name: pinyougou-cart-service
  registry:
    address: zookeeper://192.168.239.11:2181
  protocol:
    name: dubbo
    port: 20885

spring:
  profiles:
    include:
      - dao
      - common