server:
  port: 8002
spring:
    # 导入其他模块的yml配置
  profiles:
    include:
      - common
      - dao
dubbo:
  application:
    name: pinyougou-content-service
  registry:
    address: zookeeper://192.168.239.11:2181
  protocol:
    name: dubbo
    port: 20881
