server:
  port: 8001

dubbo:
  application:
    name: pinyougou-sellergoods-service
  registry:
    address: zookeeper://192.168.239.11:2181
  protocol:
    name: dubbo
    port: 20880

spring:
  profiles:
    include: dao