server:
  port: 9101

dubbo:
  application:
    name: pinyougou-shop-web
  registry:
    address: zookeeper://192.168.239.11:2181

spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

