server:
  port: 9001

dubbo:
  application:
    name: pinyougou-manager-web
  registry:
    address: zookeeper://192.168.239.11:2181

spring:
  thymeleaf:
    cache: false
  profiles:
    include: common


