server:
  port: 8005
spring:
    # 导入其他模块的yml配置
  profiles:
    include:
      - common
      - dao
  activemq:
    broker-url: tcp://192.168.239.11:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: false
# 定义队列的名称
sms: pinyougou_queue_sms

dubbo:
  application:
    name: pinyougou-user-util
  registry:
    address: zookeeper://192.168.239.11:2181
  protocol:
    name: dubbo
    port: 20884
#腾讯云短息服务
tengxunSms:
  #短信签名
  signName: 品优购
  #短信模版ID
  templateId: 528613
