server:
  port: 9003

dubbo:
  application:
    name: pinyougou-portal-web
  registry:
    address: zookeeper://192.168.239.11:2181

spring:
  thymeleaf:
    cache: false

# ===================================================================
# 分布式文件系统 FDFS 配置
# ===================================================================

fdfs:
  so-timeout: 1500 # socket连接超时时长
  connect-timeout: 2000 #连接tracker服务器超时时长
  fileServerUrl: http://192.168.239.11:80   # nginx访问地址和端口
  thumb-image: # 缩略图生成参数，可选
    width: 150
    height: 150
  tracker-list: # TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
  - 192.168.239.11:22122
  #    - 192.168.239.13:22122


